server:
    port: 8082
spring:
  security:
    oauth2:
      resourceserver:
        jwt:
          jws-algorithm: ES512
          jwk-set-uri: http://localhost:8080/openam/oauth2/realms/root/realms/sg-external/connect/jwk_uri